### ISSUE TITLE
typo: "hatag"

### ISSUE THREAD

**Issue by waldyrious** [mashiweirk/hashtagbanner#2]
The repository description and README say "hatag" rather than "hashtag".

**Comment by mashiweirk** [comment]
Oh thanks; will change soon. You going to contribute?

**Comment by waldyrious** [comment]
If I can, sure :) what is there to do?

**Comment by mashiweirk** [comment]
Fixed the hatag, awesome, a photo upload option would be cool?

**Comment by waldyrious** [comment]
Note that the "hatag" still appears on the repo description, which you have to change in the repo settings.

As for the photo upload option, you mean you want me to implement it from scratch? I honestly don't have the time or the expertise to implement major features (would gladly do it if I had a basic income, ironically enough!), but I'm willing to help in minor ways such as testing & reporting issues, translating, style edits, and minor fixes that are within my reach. Sorry if I wasn't clear before.

**Comment by hotdang-ca** [comment]
I could probably do a manual photo upload.

**Comment by mashiweirk** [comment]
Yeah, that would be awesome!

I also think moving it to another domain would help? it’s own?

**Comment by mashiweirk** [comment]
Is it fixed now?

hotting-ca said he’ll make an upload feature. I’ll let you know for testing.

**Comment by waldyrious** [comment]
> Is it fixed now?

I'm not sure if I'm making myself clear. I meant if you go to https://github.com/mashiweirk/hashtagbanner, right on top of the repository code, you can read "Adds a *hatag* banner to your fb profile. http://basicincomeproject.org/wp-content/plugins/wp-banner-plugin/banner.html". To change this, you'll need to click the "Edit" link that should appear right next to that text (sorry, I told you before it'd be in the repo settings, but apparently I misremembered)

**Comment by mashiweirk** [comment]
Hi Waldir,

    No it was me; you were clear. Should be fixed now.

Thank You,
Mark

**Comment by waldyrious** [comment]
Indeed :) I'll close this then, the remaining discussion/planning should probably be moved to another issue.
